version: '3'

services:
  app:
    image: golang:1.24
    container_name: app
    restart: always
    working_dir: /app
    ports:
      - 8080:8080
    command: >
      sh -c "go mod download && go test ./... && go run main.go"
    volumes:
      - .:/app
